### ISSUE TITLE
[edl rl] --skip=userdata does not skip userdata

### ISSUE THREAD

**Issue by Un1Gfn** [bkerler/edl#217]
device is redmi2 [wt88047](https://wiki.postmarketos.org/wiki/Xiaomi_Redmi_2_(xiaomi-wt88047)) msm8916 snapdragon410
edl version is [r299.d5ff2d4](https://github.com/bkerler/edl/tree/d5ff2d474a185a0c0df09c74dfa24eb7cfe6e9e5)

command `mkdir rl; edl rl rl/ --skip=userdata --genxml`

issue: userdata is NOT skipped

```
[...]
firehose_client - Dumped partition oem with sector count 131072 as rl/oem.bin.
firehose_client - Dumping partition userdata with sector count 27107295 as rl/userdata.bin.
firehose -
Reading from physical partition 0, sector 3670016, sectors 27107295
Progress: |...
[here lies 20 minutes]
```

how to skip userdata & save time?

**Comment by bkerler** [comment]
Userdata will never be empty as the system installs preinstalled apps on boot (that's a google based requirement). Regarding the issue with userdata skipping, I will have a look, but I think it wasn't supposed to be used with the "rl" command, only with the "r" command.

**Comment by MrCrayon** [comment]
> Userdata will never be empty as the system installs preinstalled apps on boot (that's a google based requirement). Regarding the issue with userdata skipping, I will have a look, but I think it wasn't supposed to be used with the "rl" command, only with the "r" command.

It's definitely inside `elif cmd == "rl":`
I am not familiar with python but if `for partition in partitions:` gives _partition_ as string like **userdata** I can't see why it's not working :confused: 

https://github.com/bkerler/edl/blob/01f84bf99a21ba4d378e17444a1dba7f7edb0c49/edl/Library/streaming_client.py#L161

**Comment by MrCrayon** [comment]
@Baddad23 
> The odd thing is, it skips userdata when running the command using the live dvd (2), but doesn't skip when using Ubuntu 20.04 running native on my lappy. WTF, a mystery?

Probably the DVD includes the version before this commit https://github.com/bkerler/edl/commit/4d5cb463d227956fb5b3fda23274e593eaa7448b

```diff
+                skipped = []
+                for skippart in skip:
+                    filtered = fnmatch.filter(guid_gpt.partentries, skippart)
+                    skipped.append(filtered)
                 for selpart in guid_gpt.partentries:
                     partition = guid_gpt.partentries[selpart]
                     partitionname = partition.name
-                    if partition.name in skip:
+                    if partition.name in skipped:
```

I don't know why that was changed, maybe it addresses some edge case but the problem is that while skip was an array of strings skipped is an array of arrays so the check does not work anymore.

```python
# old version
print(*skip", sep = ", ")

# prints
# 'super', 'userdata'

# new version
print(*skipped", sep = ", ")

# prints
# ['super'], ['userdata']
```

I fixed it in #235

**Comment by Baddad23** [comment]
> @Baddad23
> 
> > The odd thing is, it skips userdata when running the command using the live dvd (2), but doesn't skip when using Ubuntu 20.04 running native on my lappy. WTF, a mystery?
> 
> Probably the DVD includes the version before this commit [4d5cb46](https://github.com/bkerler/edl/commit/4d5cb463d227956fb5b3fda23274e593eaa7448b)
> 
> ```diff
> +                skipped = []
> +                for skippart in skip:
> +                    filtered = fnmatch.filter(guid_gpt.partentries, skippart)
> +                    skipped.append(filtered)
>                  for selpart in guid_gpt.partentries:
>                      partition = guid_gpt.partentries[selpart]
>                      partitionname = partition.name
> -                    if partition.name in skip:
> +                    if partition.name in skipped:
> ```
> 
> I don't know why that was changed, maybe it addresses some edge case but the problem is that while skip was an array of strings skipped is an array of arrays so the check does not work anymore.
> 
> ```python
> # old version
> print(*skip", sep = ", ")
> 
> # prints
> # 'super', 'userdata'
> 
> # new version
> print(*skipped", sep = ", ")
> 
> # prints
> # ['super'], ['userdata']
> ```
> 
> I fixed it in #235

Wanted to say thanks for the effort! Also, wanted to ask if you could send me your firehose_client.py. The reason is, I tried to match you changes to my file but the code in mine does not match up to your changes. I tested it where I though it would work but nothing. Still not skipping with this edl command: 

edl rl dumps --memory=ufs --skip=super,userdata --loader=Loaders/LG/000c30e100310000_e746e34f737403f4_fhprg.bin --genxml

Thanks in advance
Steve

**Comment by Baddad23** [comment]
Btw, here's another thought. I'm an old time programmer, mainly cobol and assembler. When I was unsure of what was in a table/buffer (in this case an exclusion list) I would through it up on a screen. To have that come up on the terminal screen as to what exactly was excluded (skipped) would probably resolve a lot of questions before they even get posted. The more info the better as there is very little documentation on this process and even fewer edl cmd examples. Many are first time users not only of this utility but also Linus in general.

**Comment by MrCrayon** [comment]
> Wanted to say thanks for the effort! Also, wanted to ask if you could send me your firehose_client.py. The reason is, I tried to match you changes to my file but the code in mine does not match up to your changes. I tested it where I though it would work but nothing. Still not skipping with this edl command:
> 
> edl rl dumps --memory=ufs --skip=super,userdata --loader=Loaders/LG/000c30e100310000_e746e34f737403f4_fhprg.bin --genxml
> 
> Thanks in advance Steve

I am on mobile now but my firehose_client is exactly what you can find in master.
https://github.com/bkerler/edl/blob/master/edlclient/Library/firehose_client.py

Maybe you have an older version, you can repeat the steps to redownload the repository and install del again.

I'm also oldish time programmer 😀
I never touched python before but it was more at first understanding which file to change if I wanted to debug because edl is installed so changing the repo does not change anything unless you build and install again.

**Comment by Baddad23** [comment]
Dude don't know what to make of it. I reinstalled in ubuntu 20.04 and still not skipping userdata. This is copy of code in "new" firehose_client.py. It damn sure looks like your change so I'm not sure?

                sfilename = os.path.join(storedir, f"gpt_backup{str(lun)}.bin")
                with open(sfilename, "wb") as write_handle:
                    write_handle.write(data[self.firehose.cfg.SECTOR_SIZE_IN_BYTES * 2:])

                if genxml:
                    guid_gpt.generate_rawprogram(lun, self.firehose.cfg.SECTOR_SIZE_IN_BYTES, storedir)
                skipped = []
                for skippart in skip:
                    filtered = fnmatch.filter(guid_gpt.partentries, skippart)
                    skipped.append(filtered)
                for partitionname in guid_gpt.partentries:
                    partition = guid_gpt.partentries[partitionname]
                    if partitionname in skipped:
                        continue
                    filename = os.path.join(storedir, partitionname + ".bin")
                    self.info(
                        f"Dumping partition {str(partition.name)} with sector count {str(partition.sectors)} " +
                        f"as {filename}.")
                    if self.firehose.cmd_read(lun, partition.sector, partition.sectors, filename):
                        self.info(f"Dumped partition {str(partition.name)} with sector count " +
                                  f"{str(partition.sectors)} as {filename}.")
            return True

**Comment by Baddad23** [comment]
Btw, have you had any luck getting this utility to run in Windows? It seems like I'm getting a driver error of some sort. I don't think it's recognizing the Sahara mode (edl, 9008) for some reason. I mean right after "device detected :)" It should recognize saharra mode.

G:\edl>edl.py rl g:\dumps --memory=ufs --skip=userdata --loader=Loaders/LG/prog__ufs_firehose_sm8250_lge.elf --genxml
Qualcomm Sahara / Firehose Client V3.53 (c) B.Kerler 2018-2021.
main
**main - [LIB]: ←[33mPlease first install libusb_win32 driver from Zadig←[0m**
main - Using loader Loaders/LG/prog__ufs_firehose_sm8250_lge.elf ...
main - Waiting for the device
main - Device detected :)
main - Unknown mode. Aborting.

**Comment by MrCrayon** [comment]
> It damn sure looks like your change so I'm not sure?

Nope, that looks like the original

Check here and remove red line and add green lines.
https://github.com/bkerler/edl/pull/235/files

After that you need to run again build and install.

> Btw, have you had any luck getting this utility to run in Windows?

Sorry, I'm on Linux.
In Windows you can check device Manager and under porta you should see a QDLoader 9008.

When I was using Windows under VirtualBox I installed QPST (Qualcomm official tool) then installed the drivers that comes with it and used QFIL included.
Dumping partitions was not working under VM and that's when I found this wonderful tool.

Depending what you are doing that tool might be easier but still quite cryptic and you can do real damage.

Better if you follow some guide specific for your device, you can search for xda-developers forum, that's the best resource in English.
